org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_version = 6.0.10
minecraft_version = 1.21.1

mod_id = create
mod_name = Create
mod_author = simibubi
mod_description = Technology that empowers the player.
mod_license = Read attached LICENSE.md

# NeoForge
# https://neoforged.net/
#neoforged updated to 26.1 for porting create to 26.1, but is not required for create to work, so it can be optionally disabled by the user if they do not want to use it, and can be re-enabled in the future if it is disabled
neo_version = 26.1.0.4-beta 

# removed parchment for 26.1 port as it is not compatible with 26.1 and has not been updated, and is not required for create to work (commented out instead of deleted in case it is updated in the future and can be re-enabled)

# Registrate
registrate_version = MC1.21-1.3.0+67

# Ponder
# https://maven.createmod.net/net/createmod/ponder/
ponder_version = 1.0.81

# Flywheel & Vanillin
# https://maven.createmod.net/dev/engine-room/flywheel/
flywheel_version = 1.0.6
flywheel_version_range = [1.0.0,2.0)
# https://maven.createmod.net/dev/engine-room/vanillin/
vanillin_version = 1.1.3-41

# Just Enough Items
# https://modrinth.com/mod/jei/versions
#jei_version = 19.21.0.247 (jei disabled for now until i port it to 26.1, as it is not required for create to work and has not been updated yet, but can be re-enabled in the future when it is updated)

# Curios
# https://modrinth.com/mod/curios/versions
# Curios updated to 15.0.0-beta.1+26.1 on 2026-03-26 for the 26.1 port, but is not required for create to work, so it can be optionally disabled by the user if they do not want to use it, and can be re-enabled in the future when it is updated for 26.1 if it is disabled
curios_version = 15.0.0-beta.1+26.1 

# Sodium
# https://modrinth.com/mod/sodium/versions
#sodium_version = 0.6.9 (sodium disabled for now until i port it to 26.1, as it is not required for create to work and has not been updated yet, but can be re-enabled in the future when it is updated)

# CC: Tweaked
# https://modrinth.com/mod/cc-tweaked/versions
#cc_tweaked_enable = true
#cc_tweaked_version = 1.116.1
#removed computer craft as it is not compatible with 26.1 and has not been updated, and is not required for create to work (commented out instead of deleted in case it is updated in the future and can be re-enabled)
# Farmer's Delight
# https://modrinth.com/mod/farmers-delight
#farmers_delight_enable = true
#farmers_delight_version = 1.21.1-1.2.9 (farmers delight disabled for now until i port it to 26.1, as it is not required for create to work and has not been updated yet, but can be re-enabled in the future when it is updated)
